### ISSUE TITLE
An `.apk` is generated for MyLoginUI

### ISSUE THREAD

**Issue by cdeutsch** [brminnick/UITestSampleApp#14]
@brminnick any idea how to reconfigure the solution so it doesn't build MyLoginUI as an `.apk`?

In the Mobile Center Integration environment it no longer allows you to download both `.apk`'s and it's picking the MyLoginUI one instead of the `UITestSampleApp` one

![image](https://cloud.githubusercontent.com/assets/404765/25999546/327603d0-36eb-11e7-8cf7-3c0323a38e41.png)

**Comment by brminnick** [comment]
Hey @cdeutsch! I'm not sure off of the top of my head. I'll look into it today!
