### ISSUE TITLE
Message: SetUp : System.NullReferenceException : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by apatelzc** [brminnick/UITestSampleApp#16]
We have tried to run the Unit testing using 

 return ConfigureApp
                        .Android
                        .PreferIdeSettings()
                        .ApkFile("com.minnick.uitestsampleapp-Signed.apk")
                        .StartApp();

but system will not able to find the .apk file and when i tried to see the exception then it's told me about some release mode disable error so event not able to find execute Exception 

Refer Snap:

![image](https://user-images.githubusercontent.com/11843493/26873215-a98742e4-4b96-11e7-8827-f9c3b80b6c91.png)

**Comment by brminnick** [comment]
HI @apatelzc! I couldn't reproduce the error using the code on the current master branch
