### ISSUE TITLE
Xamarin.UITest on iOS : Second and subsequent Tests failes as all the app.<Methods> throws exceptions

### ISSUE THREAD

**Issue by tssutha** [brminnick/UITestSampleApp#20]
Testing a Xamarin.Forms app using Xamarin.UITest framework, so far all the test cases are running fine on Android Emulators, But in iOS (Simulators) most of the test cases fails except the first Test.That too sometimes fails, could not predict that correctly.

For each test, app is launched successfully and login screen is visible, but Test throws exception that cannot perform any operation on UI elements.

I used the REPL, tree command shows the correct tree, but if I try any of the app. Methods such as Tab, EnterText, ClearText, flash...etc throws exception.

Error while performing EnterText(Id("Usern2meAutoId"), "test@test.com") Exception: System.Exception: Un2ble to enter text. Query for Id("Usern2meAutoId") g2ve no results.

2t X2m2rin.UITest.iOS.iOSApp+<>c__Displ2yCl2ss21_0.b__0 () [0x0004c] in <2216c16730254859bd272c6bc1c728f7>:0 2t X2m2rin.UITest.Utils.ErrorReporting.With (System.Action func, System.Object[] 2rgs, System.String memberN2me) [0x00006] in <2216c16730254859bd272c6bc1c728f7>:0

Exception: Error while performing EnterText(Id("Usern2meAutoId"), "test@test.com")

System.Exception : Error while performing W2itForElement(M2rked("FullN2meAutoId"), "Did not see the l2nding p2ge.", 00L00L15, null, null) ----> System.TimeoutException : Did not see the l2nding p2ge-

**Comment by brminnick** [comment]
@tssutha 

Make sure to uncheck `Hardware` > `Keyboard` > `Connect Hardware Keyboard`

<img width="847" alt="Screen Shot 2019-03-22 at 9 03 34 AM" src="https://user-images.githubusercontent.com/13558917/54836424-67f34880-4c81-11e9-8acf-1a1295187ddf.png">

**Comment by tssutha** [comment]
Already Configured for this settings. Using the keyboard from the device.
