### ISSUE TITLE
I am receiving numerous Socket Exceptions 

### ISSUE THREAD

**Issue by grockland** [brminnick/UITestSampleApp#25]
and don't know why.  I presume it is from the socket connection between the Xamarin.UITest.dll an the device.  Could you explain?
e.g. 
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in Xamarin.UITest.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in Xamarin.UITest.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
Exception thrown: 'System.AggregateException' in Xamarin.UITest.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in Xamarin.UITest.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
Exception thrown: 'System.AggregateException' in Xamarin.UITest.dll
Exception thrown: 'System.Net.Http.HttpRequestException' in Xamarin.UITest.dll

**Comment by brminnick** [comment]
I haven’t seen this error. 

Can you put together a small code sample that reproduces the error?

**Comment by grockland** [comment]
This is right out of the box.  The only change I made to the code was:

ConfigureApp.Android.InstalledApp("com.minnick.uitestsampleapp").StartApp(Xamarin.UITest.Configuration.AppDataMode.Clear);

The tests do run (some fail) however these error msgs appear often:.

Exception thrown: 'System.Exception' in Xamarin.UITest.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in
mscorlib.dll
Exception thrown: 'NUnit.Framework.Internal.NUnitException' in
nunit.framework.dll
Xamarin.UITest Information: 0 : Skipping IDE integration as important
properties are configured. To force IDE integration, add
.PreferIdeSettings() to ConfigureApp.
Xamarin.UITest Information: 0 : Android test running Xamarin.UITest
version: 3.0.4
Xamarin.UITest Information: 0 : Initializing Android app on device
1040021018049827 with installed app: com.minnick.uitestsampleapp
Xamarin.UITest Information: 0 : Skipping local screenshots. Can be enabled
with EnableScreenshots() when configuring app.
Xamarin.UITest Information: 0 : Signing apk with Xamarin keystore.
Xamarin.UITest Information: 0 : Skipping installation: Already installed.
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.Net.WebException' in System.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in System.Net.Http.dll
Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
Exception thrown: 'System.IO.IOException' in System.dll
Exception thrown: 'System.AggregateException' in mscorlib.dll
Exception thrown: 'System.ObjectDisposedException' in Xamarin.UITest.dll
Exception thrown: 'System.ObjectDisposedException' in Xamarin.UITest.dll
Exception thrown: 'System.Reflection.TargetInvocationException' in
mscorlib.dll
Exception thrown: 'NUnit.Framework.Internal.NUnitException' in
nunit.framework.dll

**Comment by grockland** [comment]
I have verified that the same error msgs appear with a different program
and device, so that it is not specifically
your program that is the problem.  I am still wondering why they appear and
if you have any insight please advise.

Glenn

**Comment by brminnick** [comment]
Thanks for the confirmation @grockland.

My guess is that you haven't [enabled developer mode](https://developer.android.com/studio/debug/dev-options#enable) on your android device.
